version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3002:3001"
    networks:
      - mono
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules

networks:
  mono:
    external:
      name: mono 
